# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos-6.4-x86_64-v20130427"

  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"

  config.vm.synced_folder "../", "/share", create: true, owner: "vagrant", group: "vagrant", mount_options: ["dmode=777,fmode=666"]

  config.vm.provider :virtualbox do |vb|
    vb.name = "vagrant-php-mecab"
  end

  config.vm.provision :shell, inline: <<-EOT

    # install git
    yum install -y git

    # install mecab
    sh /vagrant/inst_mecab.sh

    # install php
    sh /vagrant/inst_php.sh

    # install php-mecab extension
    sh /vagrant/inst_php_mecab.sh

  EOT

end
